+++ 
title = "Setup a simple blog using GitHub Pages and Hugo" 
author = "ZeStig"
published = 2024-03-26T14:39:39+05:30  
tags = ["Git", "Hugo"] 
category = "Blog"
keywords = ["Blog", "GitHub Pages"] 
description = "A quick tutorial on how to set up a blog post using Hugo, hosted on GitHub pages" 
+++


Blogs are a great way to share your thoughts, ideas, and experiences
with the world. They can be used for personal or professional purposes,
and there are blogs on just about every topic imaginable.

Hugo is a popular static site generator that can be used to create
blogs, websites, and other types of online content. It is known for its
speed, flexibility, and ease of use.

In this blog post, I will walk you through the steps of creating a blog
with Hugo. I will assume that you have some basic knowledge of Git and
the command line.

* Install hugo and git
:PROPERTIES:
:CUSTOM_ID: install-hugo-and-git
:END:
I use Arch *BTW*, and so i can install =Hugo= and =Git= from the Arch
repositories. Instructions vary depending on OS and GNU/Linux
distribution.

#+begin_src sh
sudo pacman -S hugo git
#+end_src

* Repo creation
:PROPERTIES:
:CUSTOM_ID: repo-creation
:END:
The next step involves creating public repos on GitHub. I'll be creating
2 repos, a *non-empty* repo for
[[https://github.com/zstg/zstg.github.io][GitHub Pages deployment]] and
the other for storing [[https://github.com/zstg/blog][the blog itself]].
For beginners, I recommend creating these repos from the web interface
rather than the commandline, but feel free to do it in any way you
please.

After the repos are created, clone them to your local machine:

#+begin_src sh
cd ~/Git/ # an arbitrary directory where all my Git repos live
git clone https://github.com/zstg/blog.git
cd blog
#+end_src

Now it's time to fire up the website template!

#+begin_src sh
hugo new site zstgblog # choose any name, doesn't have to be zstgblog ;)
cd zstgblog/
#+end_src

I like [[https://github.com/panr/hugo-theme-terminal][this]] particular
Hugo theme, so I'm fetching it too...

#+begin_src sh
# Note that I'm still inside the zstgblog directory.
git submodule add https://github.com/panr/hugo-theme-terminal themes/terminal
#+end_src

Next, add/modify =zstgblog/hugo.toml= like so: (obviously, replace with
the name you'd provided earlier, and modify the details below to your
liking)

#+begin_src toml
baseURL = 'https://zstg.github.io/'
languageCode = 'en-us'
paginatePath = "page"
showMenuItems = 0
theme = "terminal"
[params]
  themeColor = "blue"
  # fullWidthTheme = true
  centerTheme = true

[params.logo]
   logoText = "Stig's blog"
   logoHomeLink = "/"
#+end_src

Cool. Now we can start creating and uploading posts as we please! Run
this (in the same working directory) to create a
[[https://markdownguide.org][MarkDown]], =HTML= or
[[https://orgmode.org][Org]] file, where your blog will be stored.

#+begin_src sh
hugo new posts/nameOfFile.md
#+end_src

Edit =content/posts/nameOfFile.md= and add a /brief/ intro to your post.

Next, make the GitHub Page repo
([[https://github.com/username/username.github.io]]) a =Git submodule=
of the current repo. This is done to ensure that this repo can be used
for GitHub Pages.

#+begin_src sh
# Ensure that you're in the zstgblog directory
git submodule add https://github.com/zstg/zstg.github.io.git public
#+end_src

We can now deploy this repo to GitHub and it will automatically be
converted to a proper GitHub page powered by Hugo.

#+begin_src sh
# in zstgblog
# git rm -r --cached public
hugo 
cd public
git add .
git commit -am "Add new content"
git push
cd ..
git add .
git commit -am "Rebuilt website"
git push
#+end_src

References
